- src/MapMarker.ts
- src/components/AppMap.ts
- src/services/MapMgr.ts
Make DLC/Non DLC shirnes independantly toggleable on the map. Useful to see only DLC or non DLC shrines
> DLC/Non DLC shrines toggleable seperately

- src/components/AppMapDetailsObj.ts
- src/components/AppMapDetailsObj.vue
- src/services/MapMgr.ts
If the `drop_table` value exists in the returned object from the radar server, it formats the drop table in a `pre` tag with some minor formatting.  Format should be similar to the original raw text.
Nothing is currently done with `drop_tables`.  It would allow a bit of customization if the Actor can be `iced` or `burned` or `happyed`, ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/29)
> Added ability to show item drop tables for detail object display

- src/components/AppMap.ts
- src/components/AppMapPopup.ts
- src/components/AppMapPopup.vue
Adds Popups to edit descriptions of Markers and Polylines as referenced in #19 
Add Tooltips taken from the `title` value.
This add an AppMapPopup.vue with associated Typescript file.  This vue emits messages `title` and `text` when the values are changed to keep the GeoJSON in sync.
If the Marker structure includes `feature.properties` it will save these values to the exported file, see https://stackoverflow.com/a/35819611
I am open to improvements to the popup's style or keeping the GeoJSON `properties` in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/31)
> Add Tooltip and Popups for markers/lines

- src/components/AppMap.ts
Colors are fixed for imports and exports. Needed to set the style directly after the layer was created, but only for Polylines, not Markers.
The change from `addData()` to `geometryToLayer()` (in previous commit) broke `initGeojsonFeature()` as it expected an L.Path, but the imported GeoJSON data returns a LayerGroup/FeatureGroup not a Path. The argument to initGeojsonFeature() now "any" and checks if the functions are available before attempting to call them (`setStyle` and `bindContextMenu`).
Tested importing and exporting data with and without colors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/32)
> Fix color on import/export. Fix highlight polyline and contextmenu.

- src/components/AppMap.ts
Steps to reproduce:
- Set Map to AocField (Trial of the Sword)
- Show all objects in map unit
Expected:
Units for Trial of the Sword appear
Actual:
Nothing show up
Reported in BotW Speerunning Discord channel: trial-of the sword (on 8/20/2021) by Jhent. 
Message link: https://discord.com/channels/269611402854006785/419600864924139521/878322870898552862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/36)
> Fix "Show all objects in map unit" for AocField

- src/components/AppMap.ts
- src/components/AppMapPopup.ts
- src/components/AppMapPopup.vue
- src/util/polyline.ts
Add pathLength value to tooltip and popups. Path length is saved on data export. 
I stored the `popup` instance in the `L.Polyline | L.Marker` as it is needed to keep the `pathLength` synced in the `popup`. 
**Request**
Responding to  https://discord.com/channels/269611402854006785/360564354979987458/885657189736415293
> Would it be possible to implement a total amount of distance for all lines drawn on the object map? It'd be a simple way to compare a few branches at once without needing to pull up a calculator
**Test**
I checked this by loading the 100% route json file, exporting that, then reloading the new json file.  The exported json ata has the `pathLength` included within the Feature Properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Add path length to tooltip and popup, saved on data export

- src/components/AppMap.ts
- src/util/settings.ts
1. Remove code that output:
> Settings initialised Object { beforeSaveCallbacks ....
2. Add a check to skip printing the following message to the console:
>Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/map/z3,0,0".
createRouterError vue-router.esm.js:2065
createNavigationDuplicatedError vue-router.esm.js:2035
confirmTransition vue-router.esm.js:2328
transitionTo vue-router.esm.js:2260
replace vue-router.esm.js:2726
replace vue-router.esm.js:3039
replace vue-router.esm.js:3038
updateRoute AppMap.ts:280
initMapRouteIntegration AppMap.ts:298
mounted AppMap.ts:972
VueJS 11
initUi main.ts:40
main main.ts:19
async* main.ts:46
ts app.js:7485
__webpack_require__ app.js:790
fn app.js:101
1 app.js:7643
__webpack_require__ app.js:790
<anonymous> …
> Suppress extra messages to the console

- src/components/AppMap.ts
- src/components/AppMap.vue
- src/util/ui.ts
Adds a section to the Filter pane containing `Item Auto Placement` for Fish, Birds, Insects, Animals, Enemies, and Materials.  
Uses the Auto*.json files from the `radar` repo. (They should placed be in `game_files/ecosystem` along side the `SafeZones.json` file)
The shape's color and tooltip text are coded into the json files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/57)
> Now display auto items (Fish, Birds, Insects, ...)

- src/components/AppMap.ts
- src/components/AppMap.vue
- src/util/ui.ts
Adds the ability to change colors for 
- Polygons
- Rectangles
- Circles
- Markers
Markers are now all `L.divIcon` created using an SVG. The markers should be close to the previous png markers used by Leaflet.  
The `v-model` was removed from `<input type="color">` as it was laggy.  Should
resolve #54
To avoid unnecessary calculation, changes in color are hidden behind a `debounce`. 
These changes allow color modification without closing the color picker window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/58)
> Add color to polygons, rectangles, circles, and markers

- src/util/polyline.ts
- src/util/ui.ts
Adds a check for computing line lengths only for `L.Polyline`, but not `L.Polygon` or `L.Rectangle`
`L.Polygon` and `L.Rectangle` are derived(?) from `L.Polyline` as diagrammed below:
https://leafletjs.com/examples/extending/class-diagram.html
So checking for an `instanceof L.Polyline` returns `true` for `L.Polygons` and `L.Rectangles`.  The `leafletType()` function checks first for `L.Rectangle` and `L.Polygon`, then `L.Polyline`. See https://stackoverflow.com/a/56987060
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/59)
> Display line lengths for only polylines, not polygons or rectangles

- src/MapBase.ts
- src/MapMarker.ts
- src/components/AppMap.ts
- src/components/AppMapDetailsObj.ts
- src/components/ModalGotoCoords.ts
- src/services/MapMgr.ts
- src/util/map.ts
Updated positions and `Point` to be `[x, y, z]`.  This is in conjunction with updates on the backend where the `pos` field now returns `[x, y, z]`, y (height) added.
Checked:
- Search Results
- Add To Map (from search result)
- Marker Locations, e.g. Towers, Koroks, ...
- Field Areas and Item Auto Placement (but they should not be impacted)
- Drawing (Markers, Lines, ...) Import and Export
- Go To Coordinates
- Great Plateau Barrier
- Copy Coordinates
Functions and variables renamed from `xz` to `xyz`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/68)
> Positions are now [x,y,z] (y-added) where x:E-W z:S-N y:Up-Down

- src/MapSearch.ts
- src/components/AppMap.ts
- src/components/AppMapSettings.ts
- src/components/AppMapSettings.vue
Added option to show heights (y-values) as permanent tooltips
This option is in the Settings pane
To update the tooltip with the permanent flag, we needed to unbind() then re-bind() the tooltip with a different permanent flag value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/69)
> Added option to show heights (y-values) as permanent tooltips

- src/components/AppMapDetailsObj.ts
Add BoxWater to Area Representations
`Box` is the default Shape in 
- isAreaReprPossiblyWrong()
- addAreaMarker()
if either `params` or`params.Shape` are undefined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/70)
> Add BoxWater to Area Representations

- .env
- src/MapBase.ts
- src/services/MapMgr.ts
- src/services/MsgMgr.ts
- src/util/map.ts
Made `GAME_FILES` configurable via an `.env` file (provided). Users can create their own `.env.*` files to use a different (eg. local) URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/76)
> Configurable GAME_FILES constant

- src/components/AppMap.ts
This affects production builds; debug builds always have `no-console` and `no-debugger` disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/78)
> Tell eslint to ignore the use of console.error

- src/components/AppMap.ts
Added "Clear All" confirm dialog.
The [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) module immediately deletes all layers on the "Clear all" button click.  Leaflet.draw returns all of the deleted layers (Markers and Polylines) to the "draw:deleted" event handler. We use this to re-add the layers back if the user would like to keep the layers.
@iTNTPiston
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/81)
> Add Clear All Confirm Dialog

- src/MapSearch.ts
Change search term for Zora Monuments from `name:` to `actor:`
**Note** The src/MarSearch.ts file needs to be reformatted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/83)
> Change search term for Zora Monuments from name: to actor:

- src/components/AppMap.ts
- src/components/AppMap.vue
Fixes the error 
```
1065:54 Property 'y' does not exist on type 'Polygon | MultiPolygon'.
Property 'y' does not exist on type 'Polygon'.
1063 |     const entries = Object.entries(areas); // get the key later
1064 |     for (const [data, features] of entries) {
> 1065 |       let height = features.map((feature) => feature.y);
```
Adds documentation for 
- location
- korok_type
For the documentation I was looking for a simple and minimally intrusive way to show all of the values that can be searched for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/86)
> Fix error and add doc for location: / korok_type:

- src/components/AppMap.ts
Replace "Area ${number}" with Tower Names for the Tooltip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/89)
> Show Map Tower Names rather than Area number

- src/components/AppMapDetailsObj.ts
Add Rock Pattern Korok Representation.
I was unsure of where to place the object name arrays, `rock_target` and `rock_source` as they are used in multiple functions.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/93)
> Add Rock Pattern Korok Representation

- src/components/AppMapDetailsObj.ts
Clicking on a Korok marker was missing the data `korok_type` and `korok_id` in `this.minObj`. 
This lead to an inconsistency in the Side Pane information between clicking on a Korok marker and a search result.
This data exists in `this.obj`, so sync these two fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/105)
> Sync korok_id/type if available, was missing on korok marker click

- gen_object_meta.py
- src/components/ObjectInfo.ts
- src/components/ObjectInfo.vue
- src/services/MsgMgr.ts
Add Life/Durability and Attack/Power to ObjectInfo
Adds files:
- public/game_files/object_meta.json (attached)
- gen_object_meta.py (in commit)
Note: I had originally included the data directly as a large object in the source. I then moved it to an external file in game_files.  Another option is adding more database rows, but the level_scaling will likely be an issue.  Including it directly in the source made for simple code; the external file added some async complexity and modifies `MsgMgr`
[object_meta.json.zip](https://github.com/zeldamods/objmap/files/10181060/object_meta.json.zip)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/112)
> Add Life/Durability and Attack/Power to ObjectInfo

- src/MapBase.ts
- src/components/AppMap.ts
- src/components/AppMap.vue
Add Reference Grid based on the undiscovered map section.
- Grid is 500m x 500m (large) and 125m x 125m (small)
- Smaller Grid is shown base on Zoom level
- Tower Areas outlines are included
- Leaflet layers are created once, on-demand
- Grid is offset by 125m/2 from the top and left
- Modifies `src/MapBase.ts` to control the base map layers
Thanks to Piston for this request.
Screen shots of the UI and map views below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zeldamods/objmap/117)
> Add Reference Grid based on the undiscovered map sections
